spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: movie-fun-app-service

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

security:
    basic:
        enabled: false
